language: ruby
rvm:
- 2.3.0
after_success: coveralls

deploy:
  provider: heroku
  api_key:
    secure: I8dabfbQIS5alB0Xzn7wBy4R0YJmRjfNOAq4aqPcT46vjsZUiadV2GMThRftUFym/VVARdC9YlHRqkQlw1bzxy2mLsjMeY1MndxTUCviFvbHHCcMEaP9UKWkSFX29rilAJwhDHyv3FALuPjBHozrNsDfaf9d1Dw5Q+5GT5AXuACvr9BxHiXZQwW7iQ++IMrYu7tO8mrTzZKXoFQc7D2EYpEYWV563SKdNyqhiwjIO3cmxkB939P8LbnV5BtP7EjWczqdSKhv4nogW/MobeOrmW0zef2gup4gUM4no9GhgTdaNrDKDMXLhQcZ0HvQuQ691HW9zpAsTr2H1VukFohkQyHFxrA9Lajjm8Qbi1RV1wkSDHBIjg9ZazSm03fnlhadEFvw03zl1wICh1zAqInMZfnkqNdDZbYzDmuKtuAc0aE8GCZLU01uwcttrG3xPgX/bJpGo/qCAYwRDVI5Bw5euqyLZLO/JiNVLv8Dvi48ZoyjGlEOI8SZvJ0e8SNf6RT9Zn2sqmhYxHOvBYTNxJYK9qk19z5t/hdgAWZ55H+jMbzUWLM6JKJmcOiaC/t731/It2YR9fvMH/N6HYdueRLFBCzS2NZT4DEZQ/Wxjqh5R2p2aaYtYXmM6z66bEA0BmS5CqsmljyeEWpAnFGZIehnQIv0hBYZWaTm+hzawXOew6M=
  app: tarea2integra